// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientUser.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ClientUser.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace DataLock {

namespace {

const ::google::protobuf::Descriptor* UserAuthen_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UserAuthen_reflection_ = NULL;
const ::google::protobuf::Descriptor* ClientUserInfor_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ClientUserInfor_reflection_ = NULL;
const ::google::protobuf::Descriptor* UserSession_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  UserSession_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_ClientUser_2eproto() {
  protobuf_AddDesc_ClientUser_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ClientUser.proto");
  GOOGLE_CHECK(file != NULL);
  UserAuthen_descriptor_ = file->message_type(0);
  static const int UserAuthen_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserAuthen, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserAuthen, keyword_),
  };
  UserAuthen_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UserAuthen_descriptor_,
      UserAuthen::default_instance_,
      UserAuthen_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserAuthen, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserAuthen, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UserAuthen));
  ClientUserInfor_descriptor_ = file->message_type(1);
  static const int ClientUserInfor_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, userid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, machinecode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, machinename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, session_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, state_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, partid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, longintime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, version_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, ip_),
  };
  ClientUserInfor_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      ClientUserInfor_descriptor_,
      ClientUserInfor::default_instance_,
      ClientUserInfor_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ClientUserInfor, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(ClientUserInfor));
  UserSession_descriptor_ = file->message_type(2);
  static const int UserSession_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserSession, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserSession, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserSession, cert_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserSession, time_),
  };
  UserSession_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      UserSession_descriptor_,
      UserSession::default_instance_,
      UserSession_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserSession, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(UserSession, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(UserSession));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ClientUser_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UserAuthen_descriptor_, &UserAuthen::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    ClientUserInfor_descriptor_, &ClientUserInfor::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    UserSession_descriptor_, &UserSession::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ClientUser_2eproto() {
  delete UserAuthen::default_instance_;
  delete UserAuthen_reflection_;
  delete ClientUserInfor::default_instance_;
  delete ClientUserInfor_reflection_;
  delete UserSession::default_instance_;
  delete UserSession_reflection_;
}

void protobuf_AddDesc_ClientUser_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020ClientUser.proto\022\010DataLock\"+\n\nUserAuth"
    "en\022\014\n\004type\030\001 \002(\005\022\017\n\007keyword\030\002 \002(\t\"\254\001\n\017Cl"
    "ientUserInfor\022\016\n\006userid\030\001 \002(\005\022\023\n\013machine"
    "Code\030\002 \002(\t\022\023\n\013machineName\030\003 \002(\t\022\017\n\007sessi"
    "on\030\004 \002(\t\022\r\n\005state\030\005 \002(\005\022\016\n\006partid\030\006 \002(\005\022"
    "\022\n\nlongintime\030\007 \002(\t\022\017\n\007version\030\010 \002(\t\022\n\n\002"
    "ip\030\t \002(\t\"C\n\013UserSession\022\014\n\004type\030\001 \002(\005\022\n\n"
    "\002id\030\002 \002(\t\022\014\n\004cert\030\003 \002(\t\022\014\n\004time\030\004 \002(\tB\032\n"
    "\014com.DataLockB\nClientUser", 345);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ClientUser.proto", &protobuf_RegisterTypes);
  UserAuthen::default_instance_ = new UserAuthen();
  ClientUserInfor::default_instance_ = new ClientUserInfor();
  UserSession::default_instance_ = new UserSession();
  UserAuthen::default_instance_->InitAsDefaultInstance();
  ClientUserInfor::default_instance_->InitAsDefaultInstance();
  UserSession::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ClientUser_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ClientUser_2eproto {
  StaticDescriptorInitializer_ClientUser_2eproto() {
    protobuf_AddDesc_ClientUser_2eproto();
  }
} static_descriptor_initializer_ClientUser_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int UserAuthen::kTypeFieldNumber;
const int UserAuthen::kKeywordFieldNumber;
#endif  // !_MSC_VER

UserAuthen::UserAuthen()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DataLock.UserAuthen)
}

void UserAuthen::InitAsDefaultInstance() {
}

UserAuthen::UserAuthen(const UserAuthen& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DataLock.UserAuthen)
}

void UserAuthen::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_ = 0;
  keyword_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UserAuthen::~UserAuthen() {
  // @@protoc_insertion_point(destructor:DataLock.UserAuthen)
  SharedDtor();
}

void UserAuthen::SharedDtor() {
  if (keyword_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete keyword_;
  }
  if (this != default_instance_) {
  }
}

void UserAuthen::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserAuthen::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UserAuthen_descriptor_;
}

const UserAuthen& UserAuthen::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ClientUser_2eproto();
  return *default_instance_;
}

UserAuthen* UserAuthen::default_instance_ = NULL;

UserAuthen* UserAuthen::New() const {
  return new UserAuthen;
}

void UserAuthen::Clear() {
  if (_has_bits_[0 / 32] & 3) {
    type_ = 0;
    if (has_keyword()) {
      if (keyword_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        keyword_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UserAuthen::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DataLock.UserAuthen)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_keyword;
        break;
      }

      // required string keyword = 2;
      case 2: {
        if (tag == 18) {
         parse_keyword:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_keyword()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->keyword().data(), this->keyword().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "keyword");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DataLock.UserAuthen)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DataLock.UserAuthen)
  return false;
#undef DO_
}

void UserAuthen::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DataLock.UserAuthen)
  // required int32 type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // required string keyword = 2;
  if (has_keyword()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->keyword().data(), this->keyword().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "keyword");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->keyword(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DataLock.UserAuthen)
}

::google::protobuf::uint8* UserAuthen::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataLock.UserAuthen)
  // required int32 type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // required string keyword = 2;
  if (has_keyword()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->keyword().data(), this->keyword().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "keyword");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->keyword(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DataLock.UserAuthen)
  return target;
}

int UserAuthen::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

    // required string keyword = 2;
    if (has_keyword()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->keyword());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UserAuthen::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UserAuthen* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UserAuthen*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UserAuthen::MergeFrom(const UserAuthen& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_keyword()) {
      set_keyword(from.keyword());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UserAuthen::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserAuthen::CopyFrom(const UserAuthen& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserAuthen::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void UserAuthen::Swap(UserAuthen* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(keyword_, other->keyword_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UserAuthen::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UserAuthen_descriptor_;
  metadata.reflection = UserAuthen_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int ClientUserInfor::kUseridFieldNumber;
const int ClientUserInfor::kMachineCodeFieldNumber;
const int ClientUserInfor::kMachineNameFieldNumber;
const int ClientUserInfor::kSessionFieldNumber;
const int ClientUserInfor::kStateFieldNumber;
const int ClientUserInfor::kPartidFieldNumber;
const int ClientUserInfor::kLongintimeFieldNumber;
const int ClientUserInfor::kVersionFieldNumber;
const int ClientUserInfor::kIpFieldNumber;
#endif  // !_MSC_VER

ClientUserInfor::ClientUserInfor()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DataLock.ClientUserInfor)
}

void ClientUserInfor::InitAsDefaultInstance() {
}

ClientUserInfor::ClientUserInfor(const ClientUserInfor& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DataLock.ClientUserInfor)
}

void ClientUserInfor::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  userid_ = 0;
  machinecode_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  machinename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  session_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  state_ = 0;
  partid_ = 0;
  longintime_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

ClientUserInfor::~ClientUserInfor() {
  // @@protoc_insertion_point(destructor:DataLock.ClientUserInfor)
  SharedDtor();
}

void ClientUserInfor::SharedDtor() {
  if (machinecode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete machinecode_;
  }
  if (machinename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete machinename_;
  }
  if (session_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete session_;
  }
  if (longintime_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete longintime_;
  }
  if (version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete version_;
  }
  if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete ip_;
  }
  if (this != default_instance_) {
  }
}

void ClientUserInfor::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientUserInfor::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ClientUserInfor_descriptor_;
}

const ClientUserInfor& ClientUserInfor::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ClientUser_2eproto();
  return *default_instance_;
}

ClientUserInfor* ClientUserInfor::default_instance_ = NULL;

ClientUserInfor* ClientUserInfor::New() const {
  return new ClientUserInfor;
}

void ClientUserInfor::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<ClientUserInfor*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(userid_, state_);
    if (has_machinecode()) {
      if (machinecode_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        machinecode_->clear();
      }
    }
    if (has_machinename()) {
      if (machinename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        machinename_->clear();
      }
    }
    if (has_session()) {
      if (session_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        session_->clear();
      }
    }
    partid_ = 0;
    if (has_longintime()) {
      if (longintime_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        longintime_->clear();
      }
    }
    if (has_version()) {
      if (version_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        version_->clear();
      }
    }
  }
  if (has_ip()) {
    if (ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
      ip_->clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool ClientUserInfor::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DataLock.ClientUserInfor)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 userid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &userid_)));
          set_has_userid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_machineCode;
        break;
      }

      // required string machineCode = 2;
      case 2: {
        if (tag == 18) {
         parse_machineCode:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_machinecode()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->machinecode().data(), this->machinecode().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "machinecode");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_machineName;
        break;
      }

      // required string machineName = 3;
      case 3: {
        if (tag == 26) {
         parse_machineName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_machinename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->machinename().data(), this->machinename().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "machinename");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_session;
        break;
      }

      // required string session = 4;
      case 4: {
        if (tag == 34) {
         parse_session:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_session()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->session().data(), this->session().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "session");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_state;
        break;
      }

      // required int32 state = 5;
      case 5: {
        if (tag == 40) {
         parse_state:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &state_)));
          set_has_state();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_partid;
        break;
      }

      // required int32 partid = 6;
      case 6: {
        if (tag == 48) {
         parse_partid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &partid_)));
          set_has_partid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_longintime;
        break;
      }

      // required string longintime = 7;
      case 7: {
        if (tag == 58) {
         parse_longintime:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_longintime()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->longintime().data(), this->longintime().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "longintime");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_version;
        break;
      }

      // required string version = 8;
      case 8: {
        if (tag == 66) {
         parse_version:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->version().data(), this->version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "version");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_ip;
        break;
      }

      // required string ip = 9;
      case 9: {
        if (tag == 74) {
         parse_ip:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ip()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->ip().data(), this->ip().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "ip");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DataLock.ClientUserInfor)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DataLock.ClientUserInfor)
  return false;
#undef DO_
}

void ClientUserInfor::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DataLock.ClientUserInfor)
  // required int32 userid = 1;
  if (has_userid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->userid(), output);
  }

  // required string machineCode = 2;
  if (has_machinecode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machinecode().data(), this->machinecode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "machinecode");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->machinecode(), output);
  }

  // required string machineName = 3;
  if (has_machinename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machinename().data(), this->machinename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "machinename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->machinename(), output);
  }

  // required string session = 4;
  if (has_session()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session().data(), this->session().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->session(), output);
  }

  // required int32 state = 5;
  if (has_state()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->state(), output);
  }

  // required int32 partid = 6;
  if (has_partid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->partid(), output);
  }

  // required string longintime = 7;
  if (has_longintime()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->longintime().data(), this->longintime().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "longintime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->longintime(), output);
  }

  // required string version = 8;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->version(), output);
  }

  // required string ip = 9;
  if (has_ip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ip().data(), this->ip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->ip(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DataLock.ClientUserInfor)
}

::google::protobuf::uint8* ClientUserInfor::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataLock.ClientUserInfor)
  // required int32 userid = 1;
  if (has_userid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->userid(), target);
  }

  // required string machineCode = 2;
  if (has_machinecode()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machinecode().data(), this->machinecode().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "machinecode");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->machinecode(), target);
  }

  // required string machineName = 3;
  if (has_machinename()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->machinename().data(), this->machinename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "machinename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->machinename(), target);
  }

  // required string session = 4;
  if (has_session()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->session().data(), this->session().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "session");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->session(), target);
  }

  // required int32 state = 5;
  if (has_state()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->state(), target);
  }

  // required int32 partid = 6;
  if (has_partid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->partid(), target);
  }

  // required string longintime = 7;
  if (has_longintime()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->longintime().data(), this->longintime().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "longintime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->longintime(), target);
  }

  // required string version = 8;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->version(), target);
  }

  // required string ip = 9;
  if (has_ip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->ip().data(), this->ip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->ip(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DataLock.ClientUserInfor)
  return target;
}

int ClientUserInfor::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 userid = 1;
    if (has_userid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->userid());
    }

    // required string machineCode = 2;
    if (has_machinecode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->machinecode());
    }

    // required string machineName = 3;
    if (has_machinename()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->machinename());
    }

    // required string session = 4;
    if (has_session()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->session());
    }

    // required int32 state = 5;
    if (has_state()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->state());
    }

    // required int32 partid = 6;
    if (has_partid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->partid());
    }

    // required string longintime = 7;
    if (has_longintime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->longintime());
    }

    // required string version = 8;
    if (has_version()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->version());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required string ip = 9;
    if (has_ip()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->ip());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientUserInfor::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const ClientUserInfor* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const ClientUserInfor*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void ClientUserInfor::MergeFrom(const ClientUserInfor& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_userid()) {
      set_userid(from.userid());
    }
    if (from.has_machinecode()) {
      set_machinecode(from.machinecode());
    }
    if (from.has_machinename()) {
      set_machinename(from.machinename());
    }
    if (from.has_session()) {
      set_session(from.session());
    }
    if (from.has_state()) {
      set_state(from.state());
    }
    if (from.has_partid()) {
      set_partid(from.partid());
    }
    if (from.has_longintime()) {
      set_longintime(from.longintime());
    }
    if (from.has_version()) {
      set_version(from.version());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_ip()) {
      set_ip(from.ip());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void ClientUserInfor::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientUserInfor::CopyFrom(const ClientUserInfor& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientUserInfor::IsInitialized() const {
  if ((_has_bits_[0] & 0x000001ff) != 0x000001ff) return false;

  return true;
}

void ClientUserInfor::Swap(ClientUserInfor* other) {
  if (other != this) {
    std::swap(userid_, other->userid_);
    std::swap(machinecode_, other->machinecode_);
    std::swap(machinename_, other->machinename_);
    std::swap(session_, other->session_);
    std::swap(state_, other->state_);
    std::swap(partid_, other->partid_);
    std::swap(longintime_, other->longintime_);
    std::swap(version_, other->version_);
    std::swap(ip_, other->ip_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata ClientUserInfor::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ClientUserInfor_descriptor_;
  metadata.reflection = ClientUserInfor_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int UserSession::kTypeFieldNumber;
const int UserSession::kIdFieldNumber;
const int UserSession::kCertFieldNumber;
const int UserSession::kTimeFieldNumber;
#endif  // !_MSC_VER

UserSession::UserSession()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:DataLock.UserSession)
}

void UserSession::InitAsDefaultInstance() {
}

UserSession::UserSession(const UserSession& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DataLock.UserSession)
}

void UserSession::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_ = 0;
  id_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cert_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

UserSession::~UserSession() {
  // @@protoc_insertion_point(destructor:DataLock.UserSession)
  SharedDtor();
}

void UserSession::SharedDtor() {
  if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete id_;
  }
  if (cert_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cert_;
  }
  if (time_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete time_;
  }
  if (this != default_instance_) {
  }
}

void UserSession::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserSession::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return UserSession_descriptor_;
}

const UserSession& UserSession::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ClientUser_2eproto();
  return *default_instance_;
}

UserSession* UserSession::default_instance_ = NULL;

UserSession* UserSession::New() const {
  return new UserSession;
}

void UserSession::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    type_ = 0;
    if (has_id()) {
      if (id_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        id_->clear();
      }
    }
    if (has_cert()) {
      if (cert_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        cert_->clear();
      }
    }
    if (has_time()) {
      if (time_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        time_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool UserSession::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DataLock.UserSession)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_id;
        break;
      }

      // required string id = 2;
      case 2: {
        if (tag == 18) {
         parse_id:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->id().data(), this->id().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "id");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_cert;
        break;
      }

      // required string cert = 3;
      case 3: {
        if (tag == 26) {
         parse_cert:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cert()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->cert().data(), this->cert().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cert");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_time;
        break;
      }

      // required string time = 4;
      case 4: {
        if (tag == 34) {
         parse_time:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_time()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->time().data(), this->time().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "time");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DataLock.UserSession)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DataLock.UserSession)
  return false;
#undef DO_
}

void UserSession::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DataLock.UserSession)
  // required int32 type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // required string id = 2;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->id(), output);
  }

  // required string cert = 3;
  if (has_cert()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cert().data(), this->cert().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cert");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->cert(), output);
  }

  // required string time = 4;
  if (has_time()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->time().data(), this->time().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "time");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->time(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:DataLock.UserSession)
}

::google::protobuf::uint8* UserSession::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:DataLock.UserSession)
  // required int32 type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // required string id = 2;
  if (has_id()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->id(), target);
  }

  // required string cert = 3;
  if (has_cert()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cert().data(), this->cert().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cert");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->cert(), target);
  }

  // required string time = 4;
  if (has_time()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->time().data(), this->time().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "time");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->time(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DataLock.UserSession)
  return target;
}

int UserSession::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

    // required string id = 2;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->id());
    }

    // required string cert = 3;
    if (has_cert()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->cert());
    }

    // required string time = 4;
    if (has_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->time());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UserSession::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const UserSession* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const UserSession*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void UserSession::MergeFrom(const UserSession& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_cert()) {
      set_cert(from.cert());
    }
    if (from.has_time()) {
      set_time(from.time());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void UserSession::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserSession::CopyFrom(const UserSession& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserSession::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void UserSession::Swap(UserSession* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(id_, other->id_);
    std::swap(cert_, other->cert_);
    std::swap(time_, other->time_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata UserSession::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = UserSession_descriptor_;
  metadata.reflection = UserSession_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace DataLock

// @@protoc_insertion_point(global_scope)
